import type { Metadata } from "next";
import { MainLayout } from "@/layout/mainLayout";
import { reagonTypes } from "@/types/public/Dictionaries/dictionaries.types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: reagonTypes }>;
}) {
  const { lang } = await params;
  const isRTL = lang === "fa";

  return (
    <MainLayout lang={lang} dir={isRTL ? "rtl" : "ltr"}>
      {children}
    </MainLayout>
  );
}
