import type { Metadata } from "next";
import "./globals.css";
import ProgressBar from "@/components/ProgressBar";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const peydaFont = localFont({
  src: [
    {
      path: "../../public/fonts/peyda/Peyda-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/peyda/Peyda-Thin.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/peyda/Peyda-light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/peyda/Peyda-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/peyda/Peyda-Regular.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/peyda/Peyda-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/peyda/Peyda-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/peyda/Peyda-ExtraBold.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-peyda",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={`${peydaFont.className} font-peyda`}>
        <ProgressBar />
        {children}
      </body>
    </html>
  );
}
