import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ProgressBar from "@/components/ProgressBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const peydaFont = localFont({
  src: [
    {
      path: "./_fonts/peyda/Peyda-Thin.ttf",
      weight: "100",
    },
    {
      path: "./_fonts/peyda/Peyda-Thin.ttf",
      weight: "200",
    },
    {
      path: "./_fonts/peyda/Peyda-light.ttf",
      weight: "300",
    },
    {
      path: "./_fonts/peyda/Peyda-Regular.ttf",
      weight: "400",
    },
    {
      path: "./_fonts/peyda/Peyda-Regular.ttf",
      weight: "500",
    },
    {
      path: "./_fonts/peyda/Peyda-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "./_fonts/peyda/Peyda-Bold.ttf",
      weight: "700",
    },
    {
      path: "./_fonts/peyda/Peyda-ExtraBold.ttf",
      weight: "900",
    },
  ],
  variable: "--font-peyda",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={`${peydaFont.className}`}>
        <ProgressBar />
        {children}
      </body>
    </html>
  );
}
